name: Configuración Inicial del Curso

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Borrar archivos innecesarios
      run: |
        rm -rf .github/
        rm -rf .vscode/
        rm -rf ejemplos/
        rm -rf modulos/
        rm -rf trabajos_de_estudiantes/
        rm -f README.md

    - name: Renombrar NEW_COURSE.md a README.md
      run: |
        mv NEW_COURSE.md README.md

    - name: Agregar y comprometer cambios
      run: |
        git add .
        git commit -m "Eliminar archivos innecesarios y renombrar NEW_COURSE.md a README.md"
        git push origin main

    - name: Instrucciones
      run: |
        echo "¡Listo! Los archivos innecesarios se han eliminado y NEW_COURSE.md se ha renombrado a README.md en la rama principal de tu repositorio."
        echo "Pasos a seguir:"
        echo "1. Abre la pestaña 'Actions' en tu repositorio."
        echo "2. Selecciona el flujo de trabajo 'Configuración Inicial del Curso' en el menú de la izquierda."
        echo "3. Haz clic en el botón 'Run workflow' para iniciar el proceso de configuración inicial."
        echo "4. Una vez completado, los archivos innecesarios se habrán eliminado y NEW_COURSE.md se habrá renombrado a README.md."