name: Limpiar carpetas y archivos innecesarios

on:
  push:
    branches:
      - main

jobs:
  limpiar:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}  # Usar el token de acceso personal
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    - name: Limpiar archivos y carpetas
      run: |
        # Coloca aquí los comandos para limpiar los archivos y carpetas innecesarios
        
    - name: Commit changes
      run: |
        git add .
        git commit -m "Limpiar carpetas y archivos innecesarios"
        
    - name: Push changes
      run: |
        git push origin main

