name: Crear Nuevo Repositorio desde Plantilla

on:
  repository_dispatch:
    types:
      - create-new-repo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2

    - name: Crear Nuevo Repositorio
      run: |
        git checkout -b new-repo-setup
        rm -rf .github/ISSUE_TEMPLATE
        rm -rf ejemplos
        rm -rf trabajos_de_estudiantes
        rm -rf modulos
        rm CONTRIBUTING.md
        find . -type f ! -name 'INSTRUCCIONES.md' -delete
        find . -type d -empty -delete
        git add .
        git commit -m "Limpiar archivos y carpetas innecesarios"
        git push origin new-repo-setup

    - name: Crea un Nuevo Repositorio
      uses: repo-sync/github-repo-create@v2
      env:
        REPO_NAME: "Nuevo-Repositorio"
        REPO_PRIVATE: "false"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Crear un Despacho Personalizado
      run: |
        echo "{\"event_type\": \"create-new-repo\"}" > event.json
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -d @event.json \
          https://api.github.com/repos/$GITHUB_REPOSITORY/dispatches

